[project]
name = "batchcap"
version = "0.1.2"
description = "Cross-platform video batch screenshot tool"
requires-python = ">=3.10"
readme = "README.md"

dependencies = [
    "psutil",
    "tqdm",
]

[project.scripts]
batchcap = "batchcap.BatchCap:main"   

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
